import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faAngleDown,
    faAngleUp,
    faArrowLeft,
    faArrowRightToBracket,
    faArrowsLeftRight,
    faBars,
    faBell,
    faBurger,
    faCaretDown,
    faCaretUp,
    faCheck,
    faCirclePlus,
    faDesktop,
    faDisplay,
    faEarthAmericas,
    faEllipsis,
    faExclamation,
    faExclamationTriangle,
    faFileArrowDown,
    faFileImport,
    faHouse,
    faInbox,
    faLocationDot,
    faMagnifyingGlass,
    faMapLocation,
    faMinus,
    faMoon,
    faMugSaucer,
    faPlus,
    faShirt,
    faShop,
    faSun,
    faTags,
    faTrash,
    faTrashCan,
    faUser,
    faUserSecret,
    faUserTie,
    faWarning,
    faXmark,
} from "@fortawesome/free-solid-svg-icons";

import { faHtml5 } from "@fortawesome/free-brands-svg-icons";

import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
    faAngleDown,
    faAngleUp,
    faArrowLeft,
    faArrowsLeftRight,
    faArrowRightToBracket,
    faBars,
    faBell,
    faBurger,
    faCaretDown,
    faCaretUp,
    faCheck,
    faCirclePlus,
    faDesktop,
    faDisplay,
    faEarthAmericas,
    faEllipsis,
    faExclamation,
    faExclamationTriangle,
    faFileArrowDown,
    faFileImport,
    faInbox,
    faHouse,
    faHtml5,
    faLocationDot,
    faMagnifyingGlass,
    faMapLocation,
    faMinus,
    faMoon,
    faMugSaucer,
    faPlus,
    faShop,
    faShirt,
    faSun,
    faTags,
    faTrash,
    faTrashCan,
    faUser,
    faUserSecret,
    faUserTie,
    faWarning,
    faXmark,
);

export { FontAwesomeIcon };
